In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('베릴 후보 리스트_301_600.csv')
data

,소환사명,티어,LP,레벨,승률,아이템1,아이템2,아이템3
0,Praesens,Diamond 3,5 LP,31,70%,부패 물약,란두인의 예언,루비 수정
1,Praesens,Diamond 3,5 LP,31,70%,도란의 방패,태양불꽃 방패,서리불꽃 건틀릿
2,Praesens,Diamond 3,5 LP,31,70%,가고일 돌갑옷,삼위일체,서리벼림 손아귀
3,Tumorcio,Diamond 3,1 LP,37,58%,판금 장화,발걸음 분쇄기,덤불 조끼
4,Tumorcio,Diamond 3,1 LP,37,58%,판금 장화,발걸음 분쇄기,가시 갑옷
...,...,...,...,...,...,...,...,...
460,20pulluppergame,Platinum 1,78 LP,32,47%,광전사의 군화,크라켄 학살자,구인수의 격노검
461,20pulluppergame,Platinum 1,78 LP,32,47%,마법사의 신발,방출의 마법봉,사라진 양피지
462,Sora Riku Kairi,Platinum 1,77 LP,36,69%,스테락의 도전,수호 천사,죽음의 무도
463,Sora Riku Kairi,Platinum 1,77 LP,36,69%,충전형 물약,마법공학 로켓 벨트,마법사의 신발
464,Sora Riku Kairi,Platinum 1,77 LP,36,69%,충전형 물약,선혈포식자,제어 와드

In [3]:
filter = ['20pulluppergame', 'adeline fan acc', 'animegirl1', 'BanditosBurritos',
          'Budget Kireii', 'Carreneet', 'cat collector', 'CEO of piss',
          'CHINA ANYPERCENT', 'coingen', 'Cuda na kiju', 'dmforéloboost',
          'dRyLLeo', 'Dynasty001', 'eXzer', 'Faylennastin', 'fkin inter',
          'geilomoi', 'GGO Desu Gan', 'Hage99', 'Higennont', 'I am not Türkish',
          'IICruncyWMIII', 'iidmhxp', 'IIlIIllllIIIIIll', 'Inarmillitan',
          'Jecaetutu', 'Jeg Keder Mig XD', 'JestemKotem', 'Kanaken Raus',
          'King Rammus V', 'Korrupnot', 'lIlIIllIlIlIl', 'LXST CXNTURΥ',
          'M Huncho Birds', 'Me Bad MEntal', 'N0giz0n3', 'Not WinnabIe',
          'opous', 'ougbua', 'päikkärit', 'Pian PANINO', 'pipounn', 'pxexuirda',
          'RÐC', 'Rebidsa', 'Riås Gremôry', 'Rias Megami', 'RosamariaJesu',
          'SAUROOOOOOOOOOON', 'SCP 0988', 'Scriabin abuser', 'Sharοn99',
          'Shim Chi Buffoon', 'SILENCEE WHO', 'Skoanzil', 'SKT T1 HYZENN',
          'soft heart', 'Sora Riku Kairi', 'sugar pIum', 'supp gap hehe',
          'TheEdenPrοject', 'top diff victim1', 'TUEUR DE JUIF', 'Tumorcio',
          'TwitchTv lolasta', 'umxaslmp', 'viking matyáš', 'viper3zz', 'Vxnøm',
          'weak egg', 'Whíterοse', 'wx zhao6582123ad', 'xjsjm', 'yMyRiZKerr',
          'yusigum']
data1 = data['소환사명'].isin(filter)
data1

0      False
1      False
2      False
3       True
4       True
       ...
460     True
461     True
462     True
463     True
464     True
Name: 소환사명, Length: 465, dtype: bool

In [4]:
filteredData = data[data1].iloc[:,:5].drop_duplicates()
filteredData = filteredData.sort_values('레벨').reset_index(drop=True)
filteredData

               소환사명          티어      LP  레벨   승률
0   adeline fan acc  Platinum 1  100 LP  31  41%
1          umxaslmp  Platinum 1  100 LP  32  59%
2   20pulluppergame  Platinum 1   78 LP  32  47%
3           yusigum   Diamond 4   87 LP  33  50%
4     IICruncyWMIII   Diamond 4    1 LP  33  86%
..              ...         ...     ...  ..  ...
71         geilomoi   Diamond 4    1 LP  38  70%
72        Higennont   Diamond 4    0 LP  38  56%
73            Vxnøm  Platinum 1  100 LP  38  53%
74   TheEdenPrοject   Diamond 4    1 LP  38  65%
75    lIlIIllIlIlIl  Platinum 1  100 LP  38  58%

[76 rows x 5 columns]

In [6]:
filteredData.to_csv('final_301_600.csv', index=False, encoding='utf-8-sig')

In [8]:
pd.read_csv('final_301_600.csv')

               소환사명          티어      LP  레벨   승률
0   adeline fan acc  Platinum 1  100 LP  31  41%
1          umxaslmp  Platinum 1  100 LP  32  59%
2   20pulluppergame  Platinum 1   78 LP  32  47%
3           yusigum   Diamond 4   87 LP  33  50%
4     IICruncyWMIII   Diamond 4    1 LP  33  86%
..              ...         ...     ...  ..  ...
71         geilomoi   Diamond 4    1 LP  38  70%
72        Higennont   Diamond 4    0 LP  38  56%
73            Vxnøm  Platinum 1  100 LP  38  53%
74   TheEdenPrοject   Diamond 4    1 LP  38  65%
75    lIlIIllIlIlIl  Platinum 1  100 LP  38  58%

[76 rows x 5 columns]